[package]
name = "oso-play-omicron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
lazy_static = "1.4"
oso = "0.22"
uuid = "0.8"
